---
pakupi_domain: "pakupi.local"
pakupi_network: 192.168.64.0
pakupi_network_mask: 255.255.255.0

# DHCP Configuration
pakupi_dhcp_range:
  begin: 192.168.64.64
  end: 192.168.64.127
pakupi_dhcp_dns:
- 8.8.8.8
- 8.8.4.4
pakupi_dhcp_gateway: # TODO Implement

# NIS Configuration
pakupi_nis_domain: "nis.pakupi.local"

# Slurm Configuration
pakupi_slurm_partitions:
- mocha-worker

# NFS Configuration
pakupi_nfs_export: "/exports/pakupi"
pakupi_nfs_import: "/shared/pakupi"