---
- hosts: all
  tasks:
  - set_fact:
      nis_domain: "{{ pakupi_nis_domain }}"
      nis_master: "{{ pakupi_nis_master }}"
- hosts: mocha-master
  become: yes
  tasks:
  - name: Setup NIS server
    include_role:
      name: nis
  vars: 
    nis_role: "master"

- hosts: mocha-worker
  become: yes
  tasks:
  - name: Setup NIS client
    include_role:
      name: nis
  vars: 
    nis_role: "client"

