---
- hosts: mocha-master
  become: yes
  tasks:
  - name: Setup NIS server
    include_role:
      name: nis
  vars: 
    nis_role: "master"
    nis_domain: "nis.mocha.local"

- hosts: mocha-worker
  become: yes
  tasks:
  - name: Setup NIS client
    include_role:
      name: nis
  vars: 
    nis_role: "client"
    nis_master: "192.168.64.1"
    nis_domain: "nis.mocha.local"

