---
- hosts: mocha-master
  become: yes
  tasks:
  - name: Setup slurm controller
    include_role:
      name: galaxyproject.slurm
  - name: Create slurm run dir
    file:
      path: /var/run/slurm-llnl
      state: directory
      owner: slurm
      group: slurm
      mode: '0644'
  - name: Restart controller
    service:
      name: slurmctld
      state: started
  vars: 
    slurm_roles: ["controller"]
    slurm_create_user: no
    slurm_create_dirs: yes
    slurm_user:
      comment: "Slurm Workload Manager"
      gid: 1000
      group: user
      name: user
      uid: 1000
    slurm_nodes:
    - name: "mocha-worker"
      CoresPerSocket: 1
      Sockets: 1
      ThreadsPerCore: 1
    slurm_partitions:
    - name: pi
      Default: YES
      MaxTime: UNLIMITED
      Nodes: "mocha-worker"
    slurm_config:
      SlurmctldHost: "mocha-master"
      SlurmctldLogFile: "/var/log/slurm/slurmctld.log"
      SlurmdSpoolDir: "/var/lib/slurm/slurmd"
      SlurmdLogFile: "/var/log/slurm/slurmd.log"
      ReturnToService: 2
    slurm_munge_key: "./files/munge.key"
    slurm_config_dir: "/etc/slurm"

- hosts: mocha-worker
  become: yes
  tasks:
  - name: Setup slurm workers
    include_role:
      name: galaxyproject.slurm
  - name: Create slurm run dir
    file:
      path: /var/run/slurm-llnl
      state: directory
      owner: slurm
      group: slurm
      mode: '0644'
  - name: Create slurm lib dir
    file:
      path: /var/lib/slurm-llnl
      state: directory
      owner: slurm
      group: slurm
      mode: '0644'
  - name: Restart controller
    service:
      name: slurmd
      state: started
  vars:
    slurm_roles: ["exec"]
    slurm_create_user: no
    slurm_create_dirs: yes
    slurm_user:
      comment: "Slurm Workload Manager"
      gid: 1000
      group: user
      name: user
      uid: 1000
    slurm_nodes:
    - name: "mocha-worker"
      CoresPerSocket: 1
      Sockets: 1
      ThreadsPerCore: 1
    slurm_partitions:
    - name: pi
      Default: YES
      MaxTime: UNLIMITED
      Nodes: "mocha-worker"
    slurm_config:
      SlurmctldHost: "mocha-master"
      SlurmctldLogFile: "/var/log/slurm/slurmctld.log"
      SlurmdLogFile: "/var/log/slurm/slurmd.log"
      SlurmdSpoolDir: "/var/lib/slurm/slurmd"
      ReturnToService: 2
    slurm_munge_key: "./files/munge.key"
    slurm_config_dir: "/etc/slurm"
