---
- hosts: 
  - mocha-master
  - mocha-worker
  gather_facts: yes
  tasks:
  - name: "Set hostname to {{ inventory_hostname }}"
    become: yes
    ansible.builtin.hostname:
      name: "{{ inventory_hostname }}"
      use: systemd
  - name: Build Slurm user information
    set_fact:
      slurm_user:
        uid: "{{ hostvars[groups['mocha-master']|first].ansible_user_uid }}"
        gid: "{{ hostvars[groups['mocha-master']|first].ansible_user_gid }}"
        name: "{{ hostvars[groups['mocha-master']|first].ansible_user }}"
        group: "{{ hostvars[groups['mocha-master']|first].ansible_user }}"
      slurm_create_user: no
      slurm_create_dirs: yes
      slurm_nodes: "{{ slurm_nodes }}"
      slurm_partitions: "{{ slurm_partitions }}"
      slurm_config:
        SlurmctldHost: "{{ hostvars[groups['mocha-master']|first].inventory_hostname }}"
        SlurmctldLogFile: "/var/log/slurm/slurmctld.log"
        SlurmdSpoolDir: "/var/lib/slurm/slurmd"
        SlurmdLogFile: "/var/log/slurm/slurmd.log"
        SlurmctldPidFile: "/var/run/slurm/slurmctld.pid"
        SlurmdPidFile: "/var/run/slurm/slurmd.pid"
        StateSaveLocation: "/var/lib/slurm/slurmctld"
        ReturnToService: 2
      slurm_munge_key: "./files/munge.key"
      slurm_config_dir: "/etc/slurm"
  vars:
    slurm_partitions: "{{ lookup('template', 'slurm_partitions.yml.j2') }}"
    slurm_nodes: "{{ lookup('template', 'slurm_nodes.yml.j2') }}"
      
- hosts: mocha-master
  become: yes
  tasks:
  - name: Setup slurm controller
    include_role:
      name: galaxyproject.slurm
  - name: Create slurm run dir
    file:
      path: /var/run/slurm-llnl
      state: directory
      owner: slurm
      group: slurm
      mode: '0644'
  - name: Restart controller
    service:
      name: slurmctld
      state: started
  vars: 
    slurm_roles: ["controller"]

- hosts: mocha-worker
  become: yes
  tasks:
  - name: Setup slurm workers
    include_role:
      name: galaxyproject.slurm
  - name: Create slurm run dir
    file:
      path: /var/run/slurm-llnl
      state: directory
      owner: slurm
      group: slurm
      mode: '0644'
  - name: Create slurm lib dir
    file:
      path: /var/lib/slurm-llnl
      state: directory
      owner: slurm
      group: slurm
      mode: '0644'
  - name: Restart controller
    service:
      name: slurmd
      state: started
  vars:
    slurm_roles: ["exec"]
