---
- hosts: pakupi_master
  become: yes
  tasks:
  - name: Create export folder
    file:
      path: "{{ pakupi_nfs_export }}"
      state: directory
      mode: '0777'
  - name: Setup NFS server
    include_role:
      name: geerlingguy.nfs
  vars:
    nfs_exports:
    - "{{ pakupi_nfs_export }} *(rw,sync,no_root_squash,no_subtree_check)"
- hosts: mocha-worker
  become: yes
  tasks:
  - name: Install required NFS packages
    apt:
      name: nfs-common
      state: present
  - name: Mount NFS share
    ansible.posix.mount:
      backup: yes
      fstype: nfs
      opts: "rw,sync,hard"
      path: "{{ pakupi_nfs_import }}"
      src: "{{ hostvars[groups['pakupi_master']|first].inventory_hostname }}:{{ pakupi_nfs_export }}"
      state: mounted
