---
# TODO Mount /home as NFS directory
- hosts: pakupi_worker
  become: yes
  tasks:
  - name: Disable overlayroot
    include_tasks:
        file: "./tasks/set_cmdline_option.yaml"
    loop:
    - { name: "overlayroot", value: "disabled" }
  - reboot:

# TODO Reboot?
# TODO Add option to deactivate overlay

      