---
- hosts: all
  become: yes
  gather_facts: no
  tasks:
  - name: Remove requirement for password on sudo
    lineinfile:
      path: /etc/sudoers.d/50-mocha-nopasswd
      state: present
      regexp: '^%sudo ALL='
      line: '%sudo ALL=(ALL:ALL) NOPASSWD: ALL'
      validate: '/usr/sbin/visudo -cf %s'
      create: yes
      owner: root
      group: root
      mode: '600'

