---
- name: "Check compat directive exists for {{ item }}"
  lineinfile:
    path: /etc/nsswitch.conf
    regexp: '^{{ item }}:.*compat.*$'
    state: absent
  check_mode: yes
  register: nis_nsswitch_configured
  failed_when: false
  changed_when: not nis_nsswitch_configured.changed
- name: Add compat directive
  block:
  - name: "Insert compat directive for {{ item }}"
    lineinfile:
      path: /etc/nsswitch.conf
      regexp: '^{{ item }}:(\s*)(.*)?$'
      line: '{{ item }}:\1compat \2'
      backrefs: yes
      backup: yes
  - name: "Remove files directive for {{ item }}"
    lineinfile:
      path: /etc/nsswitch.conf
      regexp: '^{{ item }}:(\s*.*\s)?files(\s.*)?$'
      line: '{{ item }}: \1\2'
      backrefs: yes
      backup: yes
  - name: "Remove nis directive for {{ item }}"
    lineinfile:
      path: /etc/nsswitch.conf
      regexp: '^{{ item }}:(\s*.*\s)?nis(\s.*)?$'
      line: '{{ item }}: \1\2'
      backrefs: yes
      backup: yes
  when: nis_nsswitch_configured.changed
